namespace SeaPublicWebsite.BusinessLogic.Models.Enums
{
    public enum RecommendationKey
    { 
        AddLoftInsulation,
        FloorInsulationSuspendedFloor,
        UpgradeHeatingControls,
        ReplaceSingleGlazedWindowsWithDoubleOrTripleGlazing,
        InsulateCavityWalls,
        SolarElectricPanels,
        FlatRoofInsulation,
        WallInsulationBrickAgeAToD,
        WallInsulationOther,
        InsulateSolidWalls,
        FloorInsulationSolidFloor,
        DraughtproofWindowsAndDoors,
        HotWaterCylinderInsulation,
        HotWaterCylinderThermostat,
        ReplaceCondensingBoiler,
        CondensingGasBoiler,
        HighHeatRetentionStorageHeaters,
        SolarWaterHeating,
        MixerShowerHeatRecoverySystem,
        ReplaceSingleGlazedWindowsWithLowEDoubleGlazing,
        HighPerformanceExternalDoors,
        InstallHeatPump,
        InsulateYourLoft
    }
}
