{
 "title": "SEA-BETA-Production",
 "description": "Production site monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Production Site", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Production Website Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(requests{app=\"sea-beta-Production\",status_range=\"5xx\"}[30s])",
     "legendFormat": "Exported instance {{exported_instance}}"
    }
   ]
  },
  {
   "title": "Production Website Crashes",
   "type": "graph",
   "description": "Should be 0",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "crash{app=\"sea-beta-Production\"}",
     "legendFormat": "Exported instance {{exported_instance}}"
    }
   ]
  },
  {
   "title": "Production Website CPU and Memory %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cpu{app=\"sea-beta-Production\"}",
     "legendFormat": "CPU for exported instance {{exported_instance}}"
    },
    {
     "expr": "memory_utilization",
     "legendFormat": "Memory for exported instance {{exported_instance}}"
    }
   ]
  },
  {
   "title": "Production Website Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(requests{app=\"sea-beta-Production\"}[30s]))",
     "legendFormat": "Total"
    },
    {
     "expr": "rate(requests{app=\"sea-beta-Production\"}[30s])",
     "legendFormat": "{{status_range}}"
    }
   ]
  },
  {
   "title": "Production Database Deadlocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deadlocks{service=\"sea-beta-Production-db\"}",
     "legendFormat": "Deadlocks"
    }
   ]
  },
  {
   "title": "Production Database CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cpu_percent{service=\"sea-beta-Production-db\"}",
     "legendFormat": "CPU Percent"
    }
   ]
  },
  {
   "title": "Production Database Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "connections{service=\"sea-beta-Production-db\"}",
     "legendFormat": "Connections"
    }
   ]
  },
  {
   "title": "Production Database Size (bytes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dbsize_byte{service=\"sea-beta-Production-db\"}",
     "legendFormat": "Size"
    }
   ]
  }
 ]
}