using HerPublicWebsite.BusinessLogic.Models.Enums;

namespace HerPublicWebsite.BusinessLogic.Models;

public class LocalAuthorityData
{
    public enum Hug2Status
    {
        NotTakingPart,
        Pending,
        Live
    }

    public record LocalAuthorityDetails(
        string Name,
        Hug2Status Status,
        string WebsiteUrl,
        IncomeBand[] IncomeBandOptions);

    private enum IncomeThreshold
    {
        _31000,
        _34500
    }

    private static readonly Dictionary<IncomeThreshold, IncomeBand[]> IncomeBandOptions = new()
    {
        { IncomeThreshold._31000, new[] { IncomeBand.UnderOrEqualTo31000, IncomeBand.GreaterThan31000 } },
        { IncomeThreshold._34500, new[] { IncomeBand.UnderOrEqualTo34500, IncomeBand.GreaterThan34500 } }
    };

    // The list of custodian codes comes from the publicly available "Local custodian codes" download link
    // on https://www.ordnancesurvey.co.uk/business-government/tools-support/addressbase-support
    // The local authority names and websites mainly come from the local-links-manager Gov.UK service
    // https://docs.publishing.service.gov.uk/repos/local-links-manager/checking-links.html
    public static readonly Dictionary<string, LocalAuthorityDetails> LocalAuthorityDetailsByCustodianCode = new()
    {
        { "9052", new LocalAuthorityDetails("Aberdeenshire Council", Hug2Status.NotTakingPart, "https://www.aberdeenshire.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "3805", new LocalAuthorityDetails("Adur District Council", Hug2Status.Pending, "https://www.adur-worthing.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1005", new LocalAuthorityDetails("Amber Valley Borough Council", Hug2Status.Pending, "http://www.ambervalley.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "9053", new LocalAuthorityDetails("Angus Council", Hug2Status.NotTakingPart, "https://www.angus.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "9054", new LocalAuthorityDetails("Argyll and Bute Council", Hug2Status.NotTakingPart, "https://www.argyll-bute.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "3810", new LocalAuthorityDetails("Arun District Council", Hug2Status.Pending, "http://www.arun.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "3005", new LocalAuthorityDetails("Ashfield District Council", Hug2Status.Pending, "https://www.ashfield.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "2205", new LocalAuthorityDetails("Ashford Borough Council", Hug2Status.Pending, "https://www.ashford.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "3505", new LocalAuthorityDetails("Babergh District Council", Hug2Status.Live, "https://www.babergh.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "5060", new LocalAuthorityDetails("London Borough of Barking and Dagenham", Hug2Status.Pending, "https://www.lbbd.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "5090", new LocalAuthorityDetails("London Borough of Barnet", Hug2Status.Pending, "https://www.barnet.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "4405", new LocalAuthorityDetails("Barnsley Metropolitan Borough Council", Hug2Status.NotTakingPart, "https://www.barnsley.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1505", new LocalAuthorityDetails("Basildon Borough Council", Hug2Status.Pending, "https://www.basildon.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1705", new LocalAuthorityDetails("Basingstoke and Deane Borough Council", Hug2Status.Pending, "http://www.basingstoke.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "3010", new LocalAuthorityDetails("Bassetlaw District Council", Hug2Status.Pending, "https://www.bassetlaw.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "114", new LocalAuthorityDetails("Bath and North East Somerset Council", Hug2Status.Live, "http://www.bathnes.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "235", new LocalAuthorityDetails("Bedford Borough Council", Hug2Status.Pending, "https://www.bedford.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "5120", new LocalAuthorityDetails("London Borough of Bexley", Hug2Status.Pending, "https://www.bexley.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "4605", new LocalAuthorityDetails("Birmingham City Council", Hug2Status.Pending, "https://www.birmingham.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "2405", new LocalAuthorityDetails("Blaby District Council", Hug2Status.Pending, "https://www.blaby.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "2372", new LocalAuthorityDetails("Blackburn with Darwen Borough Council", Hug2Status.Live, "https://www.blackburn.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "2373", new LocalAuthorityDetails("Blackpool Borough Council", Hug2Status.Live, "https://www.blackpool.gov.uk/Home.aspx", IncomeBandOptions[IncomeThreshold._31000]) },
        { "6910", new LocalAuthorityDetails("Blaenau Gwent County Borough Council", Hug2Status.NotTakingPart, "https://www.blaenau-gwent.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1010", new LocalAuthorityDetails("Bolsover District Council", Hug2Status.NotTakingPart, "https://www.bolsover.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "4205", new LocalAuthorityDetails("Bolton Metropolitan Borough Council", Hug2Status.NotTakingPart, "http://www.bolton.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "2505", new LocalAuthorityDetails("Boston Borough Council", Hug2Status.Pending, "https://www.boston.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1260", new LocalAuthorityDetails("Bournemouth, Christchurch and Poole Council", Hug2Status.Pending, "https://www.bcpcouncil.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "335", new LocalAuthorityDetails("Bracknell Forest Council", Hug2Status.Pending, "https://www.bracknell-forest.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "4705", new LocalAuthorityDetails("City of Bradford Metropolitan District Council", Hug2Status.NotTakingPart, "https://www.bradford.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1510", new LocalAuthorityDetails("Braintree District Council", Hug2Status.Pending, "http://www.braintree.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "2605", new LocalAuthorityDetails("Breckland Council", Hug2Status.Pending, "http://www.breckland.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "5150", new LocalAuthorityDetails("London Borough of Brent", Hug2Status.Pending, "https://www.brent.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1515", new LocalAuthorityDetails("Brentwood Borough Council", Hug2Status.Pending, "http://www.brentwood.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "6915", new LocalAuthorityDetails("Bridgend County Borough Council", Hug2Status.NotTakingPart, "https://www.bridgend.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1445", new LocalAuthorityDetails("Brighton and Hove City Council", Hug2Status.Pending, "https://www.brighton-hove.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "116", new LocalAuthorityDetails("Bristol City Council", Hug2Status.Live, "https://www.bristol.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "2610", new LocalAuthorityDetails("Broadland District Council", Hug2Status.Pending, "https://www.southnorfolkandbroadland.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1805", new LocalAuthorityDetails("Bromsgrove District Council", Hug2Status.Pending, "http://www.bromsgrove.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1905", new LocalAuthorityDetails("Borough of Broxbourne", Hug2Status.Pending, "https://www.broxbourne.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "3015", new LocalAuthorityDetails("Broxtowe Borough Council", Hug2Status.Pending, "https://www.broxtowe.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "440", new LocalAuthorityDetails("Buckinghamshire Council", Hug2Status.Pending, "https://www.buckinghamshire.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "2315", new LocalAuthorityDetails("Burnley Borough Council", Hug2Status.Live, "http://www.burnley.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "4210", new LocalAuthorityDetails("Bury Metropolitan Borough Council", Hug2Status.NotTakingPart, "https://www.bury.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "6920", new LocalAuthorityDetails("Caerphilly County Borough Council", Hug2Status.NotTakingPart, "http://www.caerphilly.gov.uk", IncomeBandOptions[IncomeThreshold._31000]) },
        { "4710", new LocalAuthorityDetails("Calderdale Metropolitan Borough Council", Hug2Status.Pending, "http://www.calderdale.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "505", new LocalAuthorityDetails("Cambridge City Council", Hug2Status.Pending, "https://www.cambridge.gov.uk/", IncomeBandOptions[IncomeThreshold._34500]) }, // Part of Cambridge City Council Consortium
        { "5210", new LocalAuthorityDetails("London Borough of Camden", Hug2Status.Pending, "https://www.camden.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "3405", new LocalAuthorityDetails("Cannock Chase District Council", Hug2Status.Pending, "http://www.cannockchasedc.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "2210", new LocalAuthorityDetails("Canterbury City Council", Hug2Status.Pending, "https://www.canterbury.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "6815", new LocalAuthorityDetails("City of Cardiff Council", Hug2Status.NotTakingPart, "https://www.cardiff.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "6825", new LocalAuthorityDetails("Carmarthenshire County Council", Hug2Status.NotTakingPart, "https://www.carmarthenshire.gov.wales/home/council-services/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1520", new LocalAuthorityDetails("Castle Point Borough Council", Hug2Status.Pending, "https://www.castlepoint.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "240", new LocalAuthorityDetails("Central Bedfordshire Council", Hug2Status.NotTakingPart, "http://www.centralbedfordshire.gov.uk", IncomeBandOptions[IncomeThreshold._31000]) },
        { "6820", new LocalAuthorityDetails("Ceredigion County Council", Hug2Status.NotTakingPart, "http://www.ceredigion.gov.uk", IncomeBandOptions[IncomeThreshold._31000]) },
        { "2410", new LocalAuthorityDetails("Charnwood Borough Council", Hug2Status.Pending, "http://www.charnwood.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1525", new LocalAuthorityDetails("Chelmsford City Council", Hug2Status.Pending, "https://www.chelmsford.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1605", new LocalAuthorityDetails("Cheltenham Borough Council", Hug2Status.Live, "https://www.cheltenham.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "3105", new LocalAuthorityDetails("Cherwell District Council", Hug2Status.Live, "https://www.cherwell.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "660", new LocalAuthorityDetails("Cheshire East Council", Hug2Status.Pending, "https://www.cheshireeast.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "665", new LocalAuthorityDetails("Cheshire West and Chester Council", Hug2Status.Pending, "https://www.cheshirewestandchester.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1015", new LocalAuthorityDetails("Chesterfield Borough Council", Hug2Status.Pending, "https://www.chesterfield.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "3815", new LocalAuthorityDetails("Chichester District Council", Hug2Status.Pending, "http://www.chichester.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "2320", new LocalAuthorityDetails("Chorley Council", Hug2Status.Live, "http://www.chorley.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "9051", new LocalAuthorityDetails("Aberdeen City Council", Hug2Status.NotTakingPart, "https://www.aberdeencity.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "9059", new LocalAuthorityDetails("Dundee City Council", Hug2Status.NotTakingPart, "https://www.dundeecity.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "9064", new LocalAuthorityDetails("City of Edinburgh Council", Hug2Status.NotTakingPart, "https://www.edinburgh.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "9067", new LocalAuthorityDetails("Glasgow City Council", Hug2Status.NotTakingPart, "https://www.glasgow.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "5030", new LocalAuthorityDetails("City of London Corporation", Hug2Status.Pending, "https://www.cityoflondon.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "3455", new LocalAuthorityDetails("Stoke-on-Trent City Council", Hug2Status.NotTakingPart, "https://www.stoke.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "5990", new LocalAuthorityDetails("City of Westminster", Hug2Status.Pending, "https://www.westminster.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "9056", new LocalAuthorityDetails("Clackmannanshire Council", Hug2Status.NotTakingPart, "https://www.clacks.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1530", new LocalAuthorityDetails("Colchester Borough Council", Hug2Status.Pending, "http://www.colchester.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "6905", new LocalAuthorityDetails("Conwy County Borough Council", Hug2Status.NotTakingPart, "https://www.conwy.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "840", new LocalAuthorityDetails("Cornwall Council", Hug2Status.Live, "https://www.cornwall.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1610", new LocalAuthorityDetails("Cotswold District Council", Hug2Status.Live, "https://www.cotswold.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "4610", new LocalAuthorityDetails("Coventry City Council", Hug2Status.Pending, "https://www.coventry.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "3820", new LocalAuthorityDetails("Crawley Borough Council", Hug2Status.Pending, "https://crawley.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "5240", new LocalAuthorityDetails("London Borough of Croydon", Hug2Status.Pending, "http://www.croydon.gov.uk", IncomeBandOptions[IncomeThreshold._31000]) },
        { "940", new LocalAuthorityDetails("Cumberland Council", Hug2Status.NotTakingPart, "https://www.cumberland.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1910", new LocalAuthorityDetails("Dacorum Borough Council", Hug2Status.Pending, "http://www.dacorum.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1350", new LocalAuthorityDetails("Darlington Borough Council", Hug2Status.Pending, "https://www.darlington.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "2215", new LocalAuthorityDetails("Dartford Borough Council", Hug2Status.Live, "http://www.dartford.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "6830", new LocalAuthorityDetails("Denbighshire County Council", Hug2Status.NotTakingPart, "https://www.denbighshire.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1055", new LocalAuthorityDetails("Derby City", Hug2Status.Pending, "https://www.derby.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1045", new LocalAuthorityDetails("Derbyshire Dales District Council", Hug2Status.Pending, "https://www.derbyshiredales.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "4410", new LocalAuthorityDetails("Doncaster Metropolitan Borough Council", Hug2Status.NotTakingPart, "http://www.doncaster.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1265", new LocalAuthorityDetails("Dorset Council", Hug2Status.Live, "https://www.dorsetcouncil.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "2220", new LocalAuthorityDetails("Dover District Council", Hug2Status.Live, "http://www.dover.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "4615", new LocalAuthorityDetails("Dudley Metropolitan Borough Council", Hug2Status.Pending, "https://www.dudley.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "9058", new LocalAuthorityDetails("Dumfries and Galloway Council", Hug2Status.NotTakingPart, "https://www.dumgal.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1355", new LocalAuthorityDetails("Durham County Council", Hug2Status.Pending, "http://www.durham.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "5270", new LocalAuthorityDetails("London Borough of Ealing", Hug2Status.Pending, "http://www.ealing.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "9060", new LocalAuthorityDetails("East Ayrshire Council", Hug2Status.NotTakingPart, "https://www.east-ayrshire.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "510", new LocalAuthorityDetails("East Cambridgeshire District Council", Hug2Status.Pending, "http://www.eastcambs.gov.uk/", IncomeBandOptions[IncomeThreshold._34500]) }, // Part of Cambridge City Council Consortium
        { "1105", new LocalAuthorityDetails("East Devon District Council", Hug2Status.Live, "http://eastdevon.gov.uk", IncomeBandOptions[IncomeThreshold._31000]) },
        { "9061", new LocalAuthorityDetails("East Dunbartonshire Council", Hug2Status.NotTakingPart, "https://www.eastdunbarton.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1710", new LocalAuthorityDetails("East Hampshire District Council", Hug2Status.Pending, "http://www.easthants.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1915", new LocalAuthorityDetails("East Hertfordshire District Council", Hug2Status.Pending, "https://www.eastherts.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "2510", new LocalAuthorityDetails("East Lindsey District Council", Hug2Status.Pending, "https://www.e-lindsey.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "9062", new LocalAuthorityDetails("East Lothian Council", Hug2Status.NotTakingPart, "https://www.eastlothian.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "9063", new LocalAuthorityDetails("East Renfrewshire Council", Hug2Status.NotTakingPart, "http://www.eastrenfrewshire.gov.uk", IncomeBandOptions[IncomeThreshold._31000]) },
        { "2001", new LocalAuthorityDetails("East Riding of Yorkshire Council", Hug2Status.NotTakingPart, "http://www.eastriding.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "3410", new LocalAuthorityDetails("East Staffordshire Borough Council", Hug2Status.Pending, "https://www.eaststaffsbc.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "3540", new LocalAuthorityDetails("East Suffolk District Council", Hug2Status.Live, "https://www.eastsuffolk.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1410", new LocalAuthorityDetails("Eastbourne Borough Council", Hug2Status.Pending, "https://www.lewes-eastbourne.gov.uk", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1715", new LocalAuthorityDetails("Eastleigh Borough Council", Hug2Status.Pending, "http://www.eastleigh.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "3605", new LocalAuthorityDetails("Elmbridge Borough Council", Hug2Status.Live, "http://www.elmbridge.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "5300", new LocalAuthorityDetails("London Borough of Enfield", Hug2Status.Pending, "https://new.enfield.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1535", new LocalAuthorityDetails("Epping Forest District Council", Hug2Status.Pending, "https://www.eppingforestdc.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "3610", new LocalAuthorityDetails("Epsom and Ewell Borough Council", Hug2Status.Live, "http://www.epsom-ewell.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1025", new LocalAuthorityDetails("Erewash Borough Council", Hug2Status.Pending, "https://www.erewash.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1110", new LocalAuthorityDetails("Exeter City Council", Hug2Status.Live, "https://exeter.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "9065", new LocalAuthorityDetails("Falkirk Council", Hug2Status.NotTakingPart, "https://www.falkirk.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1720", new LocalAuthorityDetails("Fareham Borough Council", Hug2Status.Pending, "https://www.fareham.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "515", new LocalAuthorityDetails("Fenland District Council", Hug2Status.Pending, "http://www.fenland.gov.uk/", IncomeBandOptions[IncomeThreshold._34500]) }, // Part of Cambridge City Council Consortium
        { "9066", new LocalAuthorityDetails("Fife Council", Hug2Status.NotTakingPart, "https://www.fife.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "6835", new LocalAuthorityDetails("Flintshire County Council", Hug2Status.NotTakingPart, "http://www.flintshire.gov.uk", IncomeBandOptions[IncomeThreshold._31000]) },
        { "2250", new LocalAuthorityDetails("Folkestone and Hythe District Council", Hug2Status.Pending, "https://www.folkestone-hythe.gov.uk/home", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1615", new LocalAuthorityDetails("Forest of Dean District Council", Hug2Status.Live, "https://www.fdean.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "2325", new LocalAuthorityDetails("Fylde Borough Council", Hug2Status.NotTakingPart, "https://www.fylde.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "4505", new LocalAuthorityDetails("Gateshead Metropolitan Borough Council", Hug2Status.NotTakingPart, "https://www.gateshead.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "3020", new LocalAuthorityDetails("Gedling Borough Council", Hug2Status.Pending, "https://www.gedling.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1620", new LocalAuthorityDetails("Gloucester City Council", Hug2Status.Live, "http://www.gloucester.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1725", new LocalAuthorityDetails("Gosport Borough Council", Hug2Status.Pending, "https://www.gosport.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "2230", new LocalAuthorityDetails("Gravesham Borough Council", Hug2Status.Pending, "http://www.gravesham.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "2615", new LocalAuthorityDetails("Great Yarmouth Borough Council", Hug2Status.Pending, "https://www.great-yarmouth.gov.uk", IncomeBandOptions[IncomeThreshold._31000]) },
        { "5330", new LocalAuthorityDetails("Royal Borough of Greenwich", Hug2Status.Pending, "http://www.royalgreenwich.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "3615", new LocalAuthorityDetails("Guildford Borough Council", Hug2Status.Live, "http://www.guildford.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "6810", new LocalAuthorityDetails("Gwynedd Council", Hug2Status.NotTakingPart, "https://www.gwynedd.llyw.cymru/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "5360", new LocalAuthorityDetails("London Borough of Hackney", Hug2Status.Pending, "http://www.hackney.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "650", new LocalAuthorityDetails("Halton Borough Council", Hug2Status.Pending, "http://www.halton.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "5390", new LocalAuthorityDetails("London Borough of Hammersmith & Fulham", Hug2Status.Pending, "http://www.lbhf.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "2415", new LocalAuthorityDetails("Harborough District Council", Hug2Status.Pending, "http://www.harborough.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1540", new LocalAuthorityDetails("Harlow Council", Hug2Status.Pending, "http://www.harlow.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "5450", new LocalAuthorityDetails("London Borough of Harrow", Hug2Status.Pending, "https://www.harrow.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1730", new LocalAuthorityDetails("Hart District Council", Hug2Status.Pending, "https://www.hart.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "724", new LocalAuthorityDetails("Hartlepool Borough Council", Hug2Status.Pending, "http://www.hartlepool.gov.uk", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1415", new LocalAuthorityDetails("Hastings Borough Council", Hug2Status.Pending, "https://www.hastings.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1735", new LocalAuthorityDetails("Havant Borough Council", Hug2Status.Pending, "http://www.havant.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "5480", new LocalAuthorityDetails("London Borough of Havering", Hug2Status.Pending, "https://www.havering.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1850", new LocalAuthorityDetails("Herefordshire Council", Hug2Status.Pending, "https://www.herefordshire.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1920", new LocalAuthorityDetails("Hertsmere Borough Council", Hug2Status.Pending, "https://www.hertsmere.gov.uk/home.aspx", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1030", new LocalAuthorityDetails("High Peak Borough Council", Hug2Status.Pending, "https://www.highpeak.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "9068", new LocalAuthorityDetails("The Highland Council", Hug2Status.NotTakingPart, "https://www.highland.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "5510", new LocalAuthorityDetails("London Borough of Hillingdon", Hug2Status.Pending, "https://www.hillingdon.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "2420", new LocalAuthorityDetails("Hinckley and Bosworth Borough Council", Hug2Status.Pending, "https://www.hinckley-bosworth.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "3825", new LocalAuthorityDetails("Horsham District Council", Hug2Status.Pending, "https://www.horsham.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "520", new LocalAuthorityDetails("Huntingdonshire District Council", Hug2Status.Pending, "https://www.huntingdonshire.gov.uk/", IncomeBandOptions[IncomeThreshold._34500]) }, // Part of Cambridge City Council Consortium
        { "2330", new LocalAuthorityDetails("Hyndburn Borough Council", Hug2Status.Live, "https://www.hyndburnbc.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "9069", new LocalAuthorityDetails("Inverclyde Council", Hug2Status.NotTakingPart, "https://www.inverclyde.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "3515", new LocalAuthorityDetails("Ipswich Borough Council", Hug2Status.Live, "https://www.ipswich.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "6805", new LocalAuthorityDetails("Isle of Anglesey County Council", Hug2Status.NotTakingPart, "https://www.anglesey.gov.uk", IncomeBandOptions[IncomeThreshold._31000]) },
        { "2114", new LocalAuthorityDetails("Isle of Wight Council", Hug2Status.Pending, "https://www.iow.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "835", new LocalAuthorityDetails("Council of the Isles of Scilly", Hug2Status.Live, "http://www.scilly.gov.uk", IncomeBandOptions[IncomeThreshold._31000]) },
        { "5570", new LocalAuthorityDetails("London Borough of Islington", Hug2Status.Pending, "https://www.islington.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "5600", new LocalAuthorityDetails("Royal Borough of Kensington and Chelsea", Hug2Status.Pending, "https://www.rbkc.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "2635", new LocalAuthorityDetails("Borough Council of Kings Lynn and West Norfolk", Hug2Status.Pending, "http://www.west-norfolk.gov.uk", IncomeBandOptions[IncomeThreshold._31000]) },
        { "2004", new LocalAuthorityDetails("Hull City Council", Hug2Status.NotTakingPart, "https://www.hull.gov.uk", IncomeBandOptions[IncomeThreshold._31000]) },
        { "5630", new LocalAuthorityDetails("Royal Borough of Kingston upon Thames", Hug2Status.Pending, "https://www.kingston.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "4715", new LocalAuthorityDetails("Kirklees Council", Hug2Status.NotTakingPart, "https://www.kirklees.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "4305", new LocalAuthorityDetails("Knowsley Metropolitan Borough Council", Hug2Status.Pending, "http://www.knowsley.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "5660", new LocalAuthorityDetails("London Borough of Lambeth", Hug2Status.Pending, "http://www.lambeth.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "2335", new LocalAuthorityDetails("Lancaster City Council", Hug2Status.Live, "https://www.lancaster.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "4720", new LocalAuthorityDetails("Leeds City Council", Hug2Status.Pending, "https://www.leeds.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "2465", new LocalAuthorityDetails("Leicester City Council", Hug2Status.Live, "https://www.leicester.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1425", new LocalAuthorityDetails("Lewes District Council", Hug2Status.Pending, "https://www.lewes-eastbourne.gov.uk", IncomeBandOptions[IncomeThreshold._31000]) },
        { "5690", new LocalAuthorityDetails("London Borough of Lewisham", Hug2Status.Pending, "https://lewisham.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "3415", new LocalAuthorityDetails("Lichfield District Council", Hug2Status.Pending, "https://www.lichfielddc.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "2515", new LocalAuthorityDetails("City of Lincoln Council", Hug2Status.Pending, "http://www.lincoln.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "4310", new LocalAuthorityDetails("Liverpool City Council", Hug2Status.Pending, "https://liverpool.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "5180", new LocalAuthorityDetails("London Borough of Bromley", Hug2Status.Pending, "https://www.bromley.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "5420", new LocalAuthorityDetails("London Borough of Haringey", Hug2Status.Pending, "https://www.haringey.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "5540", new LocalAuthorityDetails("London Borough of Hounslow", Hug2Status.Pending, "https://www.hounslow.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "230", new LocalAuthorityDetails("Luton Borough Council", Hug2Status.NotTakingPart, "https://www.luton.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "2235", new LocalAuthorityDetails("Maidstone Borough Council", Hug2Status.Pending, "http://www.maidstone.gov.uk", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1545", new LocalAuthorityDetails("Maldon District Council", Hug2Status.Pending, "http://www.maldon.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1820", new LocalAuthorityDetails("Malvern Hills District Council", Hug2Status.Pending, "https://www.malvernhills.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "4215", new LocalAuthorityDetails("Manchester City Council", Hug2Status.Pending, "http://www.manchester.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "3025", new LocalAuthorityDetails("Mansfield District Council", Hug2Status.Pending, "https://www.mansfield.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "2280", new LocalAuthorityDetails("Medway Council", Hug2Status.Pending, "https://www.medway.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "2430", new LocalAuthorityDetails("Melton Borough Council", Hug2Status.Pending, "http://www.melton.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "6925", new LocalAuthorityDetails("Merthyr Tydfil County Borough Council", Hug2Status.NotTakingPart, "https://www.merthyr.gov.uk", IncomeBandOptions[IncomeThreshold._31000]) },
        { "5720", new LocalAuthorityDetails("London Borough of Merton", Hug2Status.Pending, "http://www.merton.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1135", new LocalAuthorityDetails("Mid Devon District Council", Hug2Status.Live, "https://www.middevon.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "3520", new LocalAuthorityDetails("Mid Suffolk District Council", Hug2Status.Live, "https://www.midsuffolk.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "3830", new LocalAuthorityDetails("Mid Sussex District Council", Hug2Status.Pending, "http://www.midsussex.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "734", new LocalAuthorityDetails("Middlesbrough Borough Council", Hug2Status.NotTakingPart, "http://www.middlesbrough.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "9070", new LocalAuthorityDetails("Midlothian Council", Hug2Status.NotTakingPart, "https://www.midlothian.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "435", new LocalAuthorityDetails("Milton Keynes Council", Hug2Status.Pending, "https://www.milton-keynes.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "3620", new LocalAuthorityDetails("Mole Valley District Council", Hug2Status.Live, "https://www.molevalley.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "6840", new LocalAuthorityDetails("Monmouthshire County Council", Hug2Status.NotTakingPart, "https://www.monmouthshire.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "9071", new LocalAuthorityDetails("The Moray Council", Hug2Status.NotTakingPart, "http://www.moray.gov.uk", IncomeBandOptions[IncomeThreshold._31000]) },
        { "6930", new LocalAuthorityDetails("Neath Port Talbot County Borough Council", Hug2Status.NotTakingPart, "http://www.neath-porttalbot.gov.uk", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1740", new LocalAuthorityDetails("New Forest District Council", Hug2Status.Pending, "https://www.newforest.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "3030", new LocalAuthorityDetails("Newark and Sherwood District Council", Hug2Status.Pending, "https://www.newark-sherwooddc.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "4510", new LocalAuthorityDetails("Newcastle City Council", Hug2Status.Live, "https://www.newcastle.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "3420", new LocalAuthorityDetails("Newcastle-under-Lyme District Council", Hug2Status.Pending, "https://www.newcastle-staffs.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "5750", new LocalAuthorityDetails("London Borough of Newham", Hug2Status.Pending, "https://www.newham.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "6935", new LocalAuthorityDetails("Newport City Council", Hug2Status.NotTakingPart, "https://www.newport.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "9072", new LocalAuthorityDetails("North Ayrshire Council", Hug2Status.NotTakingPart, "https://www.north-ayrshire.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1115", new LocalAuthorityDetails("North Devon Council", Hug2Status.Live, "http://www.northdevon.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1035", new LocalAuthorityDetails("North East Derbyshire District Council", Hug2Status.NotTakingPart, "https://www.ne-derbyshire.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "2002", new LocalAuthorityDetails("North East Lincolnshire Council", Hug2Status.Pending, "http://www.nelincs.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1925", new LocalAuthorityDetails("North Hertfordshire District Council", Hug2Status.Pending, "http://www.north-herts.gov.uk", IncomeBandOptions[IncomeThreshold._31000]) },
        { "2520", new LocalAuthorityDetails("North Kesteven District Council", Hug2Status.Pending, "https://www.n-kesteven.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "9073", new LocalAuthorityDetails("North Lanarkshire Council", Hug2Status.NotTakingPart, "https://www.northlanarkshire.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "2003", new LocalAuthorityDetails("North Lincolnshire Council", Hug2Status.Pending, "https://www.northlincs.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "2620", new LocalAuthorityDetails("North Norfolk District Council", Hug2Status.Pending, "https://www.north-norfolk.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "2840", new LocalAuthorityDetails("North Northamptonshire Council", Hug2Status.Pending, "https://www.northnorthants.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "121", new LocalAuthorityDetails("North Somerset Council", Hug2Status.Live, "http://www.n-somerset.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "4515", new LocalAuthorityDetails("North Tyneside Council", Hug2Status.Pending, "https://my.northtyneside.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "3705", new LocalAuthorityDetails("North Warwickshire Borough Council", Hug2Status.Pending, "https://www.northwarks.gov.uk/site/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "2435", new LocalAuthorityDetails("North West Leicestershire District Council", Hug2Status.Pending, "http://www.nwleics.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "2745", new LocalAuthorityDetails("North Yorkshire County Council", Hug2Status.Pending, "http://www.northyorks.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "2935", new LocalAuthorityDetails("Northumberland County Council", Hug2Status.Pending, "http://www.northumberland.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "2625", new LocalAuthorityDetails("Norwich City Council", Hug2Status.Pending, "http://www.norwich.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "3060", new LocalAuthorityDetails("Nottingham City Council", Hug2Status.Pending, "https://www.nottinghamcity.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "3710", new LocalAuthorityDetails("Nuneaton and Bedworth Borough Council", Hug2Status.Pending, "https://www.nuneatonandbedworth.gov.uk/site/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "2440", new LocalAuthorityDetails("Oadby and Wigston District Council", Hug2Status.Pending, "http://oadby-wigston.gov.uk/Home/Home.aspx", IncomeBandOptions[IncomeThreshold._31000]) },
        { "4220", new LocalAuthorityDetails("Oldham Metropolitan Borough Council", Hug2Status.NotTakingPart, "https://www.oldham.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "7655", new LocalAuthorityDetails("Ordnance Survey", Hug2Status.NotTakingPart, "", IncomeBandOptions[IncomeThreshold._31000]) },
        { "9000", new LocalAuthorityDetails("Orkney Islands Council", Hug2Status.NotTakingPart, "https://www.orkney.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "3110", new LocalAuthorityDetails("Oxford City Council", Hug2Status.Pending, "https://www.oxford.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "6845", new LocalAuthorityDetails("Pembrokeshire County Council", Hug2Status.NotTakingPart, "http://www.pembrokeshire.gov.uk", IncomeBandOptions[IncomeThreshold._31000]) },
        { "2340", new LocalAuthorityDetails("Pendle Borough Council", Hug2Status.Live, "https://www.pendle.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "9074", new LocalAuthorityDetails("Perth and Kinross Council", Hug2Status.NotTakingPart, "https://www.pkc.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "540", new LocalAuthorityDetails("Peterborough City Council", Hug2Status.Pending, "http://www.peterborough.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1160", new LocalAuthorityDetails("Plymouth City Council", Hug2Status.Live, "https://www.plymouth.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1775", new LocalAuthorityDetails("Portsmouth City Council", Hug2Status.Pending, "https://www.portsmouth.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "6850", new LocalAuthorityDetails("Powys County Council", Hug2Status.NotTakingPart, "http://www.powys.gov.uk", IncomeBandOptions[IncomeThreshold._31000]) },
        { "2345", new LocalAuthorityDetails("Preston City Council", Hug2Status.Live, "https://www.preston.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "345", new LocalAuthorityDetails("Reading Borough Council", Hug2Status.Pending, "https://www.reading.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "5780", new LocalAuthorityDetails("London Borough of Redbridge", Hug2Status.Pending, "https://www.redbridge.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "728", new LocalAuthorityDetails("Redcar and Cleveland Borough Council", Hug2Status.Pending, "https://www.redcar-cleveland.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1825", new LocalAuthorityDetails("Redditch Borough Council", Hug2Status.Pending, "https://www.redditchbc.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "3625", new LocalAuthorityDetails("Reigate and Banstead Borough Council", Hug2Status.Live, "https://www.reigate-banstead.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "9075", new LocalAuthorityDetails("Renfrewshire Council", Hug2Status.NotTakingPart, "https://www.renfrewshire.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "6940", new LocalAuthorityDetails("Rhondda Cynon Taf County Borough Council", Hug2Status.NotTakingPart, "https://www.rctcbc.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "2350", new LocalAuthorityDetails("Ribble Valley Borough Council", Hug2Status.Live, "https://www.ribblevalley.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "5810", new LocalAuthorityDetails("London Borough of Richmond upon Thames", Hug2Status.Pending, "http://www.richmond.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "4225", new LocalAuthorityDetails("Rochdale Metropolitan Borough Council", Hug2Status.Live, "http://www.rochdale.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1550", new LocalAuthorityDetails("Rochford District Council", Hug2Status.Pending, "https://www.rochford.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "2355", new LocalAuthorityDetails("Rossendale Borough Council", Hug2Status.Live, "https://www.rossendale.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1430", new LocalAuthorityDetails("Rother District Council", Hug2Status.Pending, "http://www.rother.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "4415", new LocalAuthorityDetails("Rotherham Metropolitan Borough Council", Hug2Status.NotTakingPart, "https://www.rotherham.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "3715", new LocalAuthorityDetails("Rugby Borough Council", Hug2Status.Pending, "http://www.rugby.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "3630", new LocalAuthorityDetails("Runnymede Borough Council", Hug2Status.Live, "https://www.runnymede.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "3040", new LocalAuthorityDetails("Rushcliffe Borough Council", Hug2Status.Pending, "http://www.rushcliffe.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1750", new LocalAuthorityDetails("Rushmoor Borough Council", Hug2Status.Pending, "http://www.rushmoor.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "2470", new LocalAuthorityDetails("Rutland County Council", Hug2Status.Pending, "https://www.rutland.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "4230", new LocalAuthorityDetails("Salford City Council", Hug2Status.NotTakingPart, "https://www.salford.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "4620", new LocalAuthorityDetails("Sandwell Metropolitan Borough Council", Hug2Status.Pending, "http://www.sandwell.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "9055", new LocalAuthorityDetails("Scottish Borders Council", Hug2Status.NotTakingPart, "https://www.scotborders.gov.uk", IncomeBandOptions[IncomeThreshold._31000]) },
        { "4320", new LocalAuthorityDetails("Sefton Metropolitan Borough Council", Hug2Status.Pending, "https://www.sefton.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "2245", new LocalAuthorityDetails("Sevenoaks District Council", Hug2Status.Live, "http://www.sevenoaks.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "4420", new LocalAuthorityDetails("Sheffield City Council", Hug2Status.Live, "https://www.sheffield.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "9010", new LocalAuthorityDetails("Shetland Islands Council", Hug2Status.NotTakingPart, "https://www.shetland.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "3245", new LocalAuthorityDetails("Shropshire Council", Hug2Status.Live, "http://www.shropshire.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "350", new LocalAuthorityDetails("Slough Borough Council", Hug2Status.Pending, "https://www.slough.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "4625", new LocalAuthorityDetails("Solihull Metropolitan Borough Council", Hug2Status.Pending, "https://www.solihull.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "3300", new LocalAuthorityDetails("Somerset Council", Hug2Status.Pending, "https://www.somerset.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) }, // Somerset appears to now cover Mendip, Sedgemoor, Somerset West and Taunton, and South Somerset. 
        { "9076", new LocalAuthorityDetails("South Ayrshire Council", Hug2Status.NotTakingPart, "https://www.south-ayrshire.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "530", new LocalAuthorityDetails("South Cambridgeshire District Council", Hug2Status.Pending, "http://www.scambs.gov.uk/", IncomeBandOptions[IncomeThreshold._34500]) }, // Part of Cambridge City Council Consortium
        { "1040", new LocalAuthorityDetails("South Derbyshire District Council", Hug2Status.Pending, "https://www.southderbyshire.gov.uk", IncomeBandOptions[IncomeThreshold._31000]) },
        { "119", new LocalAuthorityDetails("South Gloucestershire Council", Hug2Status.Live, "http://www.southglos.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1125", new LocalAuthorityDetails("South Hams District Council", Hug2Status.Pending, "http://www.southhams.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "2525", new LocalAuthorityDetails("South Holland District Council", Hug2Status.Pending, "https://www.sholland.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "2530", new LocalAuthorityDetails("South Kesteven District Council", Hug2Status.Pending, "http://www.southkesteven.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "9077", new LocalAuthorityDetails("South Lanarkshire Council", Hug2Status.NotTakingPart, "https://www.southlanarkshire.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "2630", new LocalAuthorityDetails("South Norfolk District Council", Hug2Status.Pending, "https://www.southnorfolkandbroadland.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "3115", new LocalAuthorityDetails("South Oxfordshire District Council", Hug2Status.Live, "http://www.southoxon.gov.uk", IncomeBandOptions[IncomeThreshold._31000]) },
        { "2360", new LocalAuthorityDetails("South Ribble Borough Council", Hug2Status.Live, "http://www.southribble.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "3430", new LocalAuthorityDetails("South Staffordshire Council", Hug2Status.Pending, "https://www.sstaffs.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "4520", new LocalAuthorityDetails("South Tyneside Council", Hug2Status.NotTakingPart, "http://www.southtyneside.gov.uk", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1780", new LocalAuthorityDetails("Southampton City Council", Hug2Status.Pending, "http://www.southampton.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1590", new LocalAuthorityDetails("Southend-on-Sea Borough Council", Hug2Status.Pending, "http://www.southend.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "5840", new LocalAuthorityDetails("London Borough of Southwark", Hug2Status.Pending, "https://www.southwark.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "3635", new LocalAuthorityDetails("Spelthorne Borough Council", Hug2Status.Live, "http://www.spelthorne.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1930", new LocalAuthorityDetails("St Albans City and District Council", Hug2Status.Pending, "https://www.stalbans.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "4315", new LocalAuthorityDetails("St Helens Council", Hug2Status.Pending, "https://www.sthelens.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "3425", new LocalAuthorityDetails("Stafford Borough Council", Hug2Status.Pending, "https://www.staffordbc.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "3435", new LocalAuthorityDetails("Staffordshire Moorlands District Council", Hug2Status.Pending, "https://www.staffsmoorlands.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1935", new LocalAuthorityDetails("Stevenage Borough Council", Hug2Status.Pending, "https://www.stevenage.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "9078", new LocalAuthorityDetails("Stirling Council", Hug2Status.NotTakingPart, "https://stirling.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "4235", new LocalAuthorityDetails("Stockport Metropolitan Borough Council", Hug2Status.NotTakingPart, "https://www.stockport.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "738", new LocalAuthorityDetails("Stockton-on-Tees Borough Council", Hug2Status.Pending, "https://www.stockton.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "3720", new LocalAuthorityDetails("Stratford-on-Avon District Council", Hug2Status.Pending, "https://www.stratford.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1625", new LocalAuthorityDetails("Stroud District Council", Hug2Status.Live, "http://www.stroud.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "4525", new LocalAuthorityDetails("Sunderland City Council", Hug2Status.NotTakingPart, "https://www.sunderland.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "3640", new LocalAuthorityDetails("Surrey Heath Borough Council", Hug2Status.Live, "https://www.surreyheath.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "5870", new LocalAuthorityDetails("London Borough of Sutton", Hug2Status.Pending, "https://www.sutton.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "2255", new LocalAuthorityDetails("Swale Borough Council", Hug2Status.Pending, "http://www.swale.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "6855", new LocalAuthorityDetails("City and County of Swansea Council", Hug2Status.NotTakingPart, "https://www.swansea.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "3935", new LocalAuthorityDetails("Swindon Borough Council", Hug2Status.NotTakingPart, "https://www.swindon.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "4240", new LocalAuthorityDetails("Tameside Metropolitan Borough Council", Hug2Status.NotTakingPart, "http://www.tameside.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "3445", new LocalAuthorityDetails("Tamworth Borough Council", Hug2Status.Pending, "https://www.tamworth.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "3645", new LocalAuthorityDetails("Tandridge District Council", Hug2Status.Live, "https://www.tandridge.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1130", new LocalAuthorityDetails("Teignbridge District Council", Hug2Status.Live, "http://www.teignbridge.gov.uk", IncomeBandOptions[IncomeThreshold._31000]) },
        { "3240", new LocalAuthorityDetails("Telford & Wrekin Council", Hug2Status.Pending, "http://www.telford.gov.uk", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1560", new LocalAuthorityDetails("Tendring District Council", Hug2Status.Pending, "http://www.tendringdc.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1760", new LocalAuthorityDetails("Test Valley Borough Council", Hug2Status.Pending, "https://www.testvalley.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1630", new LocalAuthorityDetails("Tewkesbury Borough Council", Hug2Status.Live, "https://tewkesbury.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "2260", new LocalAuthorityDetails("Thanet District Council", Hug2Status.Pending, "http://thanet.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1940", new LocalAuthorityDetails("Three Rivers District Council", Hug2Status.NotTakingPart, "http://www.threerivers.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1595", new LocalAuthorityDetails("Thurrock Council", Hug2Status.Pending, "http://www.thurrock.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "2265", new LocalAuthorityDetails("Tonbridge and Malling Borough Council", Hug2Status.Pending, "https://www.tmbc.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1165", new LocalAuthorityDetails("Torbay Council", Hug2Status.Live, "http://www.torbay.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "6945", new LocalAuthorityDetails("Torfaen County Borough Council", Hug2Status.NotTakingPart, "http://www.torfaen.gov.uk", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1145", new LocalAuthorityDetails("Torridge District Council", Hug2Status.Live, "https://www.torridge.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "5900", new LocalAuthorityDetails("London Borough of Tower Hamlets", Hug2Status.Pending, "http://www.towerhamlets.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "4245", new LocalAuthorityDetails("Trafford Metropolitan Borough Council", Hug2Status.NotTakingPart, "http://www.trafford.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "2270", new LocalAuthorityDetails("Tunbridge Wells Borough Council", Hug2Status.Pending, "https://www.tunbridgewells.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1570", new LocalAuthorityDetails("Uttlesford District Council", Hug2Status.Pending, "https://www.uttlesford.gov.uk/home", IncomeBandOptions[IncomeThreshold._31000]) },
        { "6950", new LocalAuthorityDetails("Vale of Glamorgan Council", Hug2Status.NotTakingPart, "https://valeofglamorgan.gov.uk/en/index.aspx", IncomeBandOptions[IncomeThreshold._31000]) },
        { "3120", new LocalAuthorityDetails("Vale of White Horse District Council", Hug2Status.Live, "http://www.whitehorsedc.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "4725", new LocalAuthorityDetails("Wakefield Metropolitan District Council", Hug2Status.Live, "https://www.wakefield.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "4630", new LocalAuthorityDetails("Walsall Metropolitan Borough Council", Hug2Status.Live, "https://go.walsall.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "5930", new LocalAuthorityDetails("London Borough of Waltham Forest", Hug2Status.Pending, "https://www.walthamforest.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "5960", new LocalAuthorityDetails("London Borough of Wandsworth", Hug2Status.Pending, "https://www.wandsworth.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "655", new LocalAuthorityDetails("Warrington Borough Council", Hug2Status.NotTakingPart, "https://www.warrington.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "3725", new LocalAuthorityDetails("Warwick District Council", Hug2Status.Pending, "http://www.warwickdc.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1945", new LocalAuthorityDetails("Watford Borough Council", Hug2Status.NotTakingPart, "https://www.watford.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "3650", new LocalAuthorityDetails("Waverley Borough Council", Hug2Status.Live, "https://www.waverley.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1435", new LocalAuthorityDetails("Wealden District Council", Hug2Status.Live, "https://www.wealden.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1950", new LocalAuthorityDetails("Welwyn Hatfield Council", Hug2Status.Pending, "https://www.welhat.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "340", new LocalAuthorityDetails("West Berkshire Council", Hug2Status.Pending, "http://www.westberks.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1150", new LocalAuthorityDetails("West Devon Borough Council", Hug2Status.Pending, "http://www.westdevon.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "9057", new LocalAuthorityDetails("West Dunbartonshire Council", Hug2Status.NotTakingPart, "https://www.west-dunbarton.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "2365", new LocalAuthorityDetails("West Lancashire Borough Council", Hug2Status.Live, "http://www.westlancs.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "2535", new LocalAuthorityDetails("West Lindsey District Council", Hug2Status.Pending, "https://www.west-lindsey.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "9079", new LocalAuthorityDetails("West Lothian Council", Hug2Status.NotTakingPart, "https://www.westlothian.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "2845", new LocalAuthorityDetails("West Northamptonshire Council", Hug2Status.Pending, "https://www.westnorthants.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "3125", new LocalAuthorityDetails("West Oxfordshire District Council", Hug2Status.Live, "https://www.westoxon.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "3545", new LocalAuthorityDetails("West Suffolk District Council", Hug2Status.Live, "https://www.westsuffolk.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "9020", new LocalAuthorityDetails("Comhairle nan Eilean Siar", Hug2Status.NotTakingPart, "https://www.cne-siar.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "935", new LocalAuthorityDetails("Westmorland and Furness Council", Hug2Status.NotTakingPart, "https://www.westmorlandandfurness.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "4250", new LocalAuthorityDetails("Wigan Metropolitan Borough Council", Hug2Status.NotTakingPart, "http://www.wigan.gov.uk", IncomeBandOptions[IncomeThreshold._31000]) },
        { "3940", new LocalAuthorityDetails("Wiltshire Council", Hug2Status.Pending, "https://www.wiltshire.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1765", new LocalAuthorityDetails("Winchester City Council", Hug2Status.Pending, "https://www.winchester.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "355", new LocalAuthorityDetails("Royal Borough of Windsor and Maidenhead", Hug2Status.Pending, "http://www.rbwm.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "4325", new LocalAuthorityDetails("Wirral Council", Hug2Status.Pending, "http://www.wirral.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "3655", new LocalAuthorityDetails("Woking Borough Council", Hug2Status.Live, "https://www.woking.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "360", new LocalAuthorityDetails("Wokingham Borough Council", Hug2Status.Pending, "https://www.wokingham.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "4635", new LocalAuthorityDetails("City of Wolverhampton Council", Hug2Status.Pending, "http://www.wolverhampton.gov.uk", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1835", new LocalAuthorityDetails("Worcester City Council", Hug2Status.Pending, "http://www.worcester.gov.uk", IncomeBandOptions[IncomeThreshold._31000]) },
        { "3835", new LocalAuthorityDetails("Worthing Borough Council", Hug2Status.Pending, "https://www.adur-worthing.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "6955", new LocalAuthorityDetails("Wrexham County Borough Council", Hug2Status.NotTakingPart, "http://www.wrexham.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1840", new LocalAuthorityDetails("Wychavon District Council", Hug2Status.Pending, "http://www.wychavon.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "2370", new LocalAuthorityDetails("Wyre Council", Hug2Status.Live, "http://www.wyre.gov.uk", IncomeBandOptions[IncomeThreshold._31000]) },
        { "1845", new LocalAuthorityDetails("Wyre Forest District Council", Hug2Status.Pending, "https://www.wyreforestdc.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
        { "2741", new LocalAuthorityDetails("City of York Council", Hug2Status.Pending, "https://www.york.gov.uk/", IncomeBandOptions[IncomeThreshold._31000]) },
    };
}

