using System.Collections.Generic;

namespace Tests.BusinessLogic.Models.ExpectedLocalAuthorityData;

internal static class LocalAuthorityConsortiums
{
    internal static Dictionary<string, string> ConsortiumsByCustodianCode()
    {
        return new Dictionary<string, string>
        {
            { "9052", null },
            { "3805", "Portsmouth City Council" },
            { "1005", "Midlands Net Zero Hub" },
            { "9053", null },
            { "9054", null },
            { "3810", "Portsmouth City Council" },
            { "3005", "Midlands Net Zero Hub" },
            { "2205", "Cambridgeshire and Peterborough Combined Authority" },
            { "3505", "Suffolk County Council" },
            { "5060", "Greater London Authority" },
            { "5090", "Greater London Authority" },
            { "4405", null },
            { "1505", null },
            { "1705", "Portsmouth City Council" },
            { "3010", "Midlands Net Zero Hub" },
            { "114", "Bristol City Council" },
            { "235", "Cambridgeshire and Peterborough Combined Authority" },
            { "5120", "Greater London Authority" },
            { "4605", "Midlands Net Zero Hub" },
            { "2405", "Midlands Net Zero Hub" },
            { "2372", "Blackpool Council" },
            { "2373", "Blackpool Council" },
            { "6910", null },
            { "1010", null },
            { "4205", null },
            { "2505", "Midlands Net Zero Hub" },
            { "1260", "Dorset Council" },
            { "335", "Cambridgeshire and Peterborough Combined Authority" },
            { "4705", null },
            { "1510", "Cambridgeshire and Peterborough Combined Authority" },
            { "2605", "Broadland District Council" },
            { "5150", "Greater London Authority" },
            { "1515", "Cambridgeshire and Peterborough Combined Authority" },
            { "6915", null },
            { "1445", "Portsmouth City Council" },
            { "116", "Bristol City Council" },
            { "2610", "Broadland District Council" },
            { "1805", "Midlands Net Zero Hub" },
            { "1905", "Cambridgeshire and Peterborough Combined Authority" },
            { "3015", "Midlands Net Zero Hub" },
            { "440", "Cambridgeshire and Peterborough Combined Authority" },
            { "2315", "Blackpool Council" },
            { "4210", null },
            { "6920", null },
            { "4710", null },
            { "505", "Cambridge City Council" },
            { "5210", "Greater London Authority" },
            { "3405", "Midlands Net Zero Hub" },
            { "2210", "Cambridgeshire and Peterborough Combined Authority" },
            { "6815", null },
            { "6825", null },
            { "1520", "Cambridgeshire and Peterborough Combined Authority" },
            { "240", null },
            { "6820", null },
            { "2410", "Midlands Net Zero Hub" },
            { "1525", "Cambridgeshire and Peterborough Combined Authority" },
            { "1605", "Stroud District Council" },
            { "3105", "Oxfordshire County Council" },
            { "660", "Cheshire East Council" },
            { "665", "Cheshire East Council" },
            { "1015", "Midlands Net Zero Hub" },
            { "3815", "Portsmouth City Council" },
            { "2320", "Blackpool Council" },
            { "9051", null },
            { "9059", null },
            { "9064", null },
            { "9067", null },
            { "5030", "Greater London Authority" },
            { "3455", null },
            { "5990", "Greater London Authority" },
            { "9056", null },
            { "1530", "Cambridgeshire and Peterborough Combined Authority" },
            { "6905", null },
            { "840", "Cornwall Council and Council of the Isles of Scilly" },
            { "1610", "Stroud District Council" },
            { "4610", "Midlands Net Zero Hub" },
            { "3820", "Portsmouth City Council" },
            { "5240", "Portsmouth City Council" },
            { "940", "Cumberland Council and Westmoreland and Furness" },
            { "1910", "Cambridgeshire and Peterborough Combined Authority" },
            { "1350", "Darlington Borough Council" },
            { "2215", "Dartford Borough Council" },
            { "6830", null },
            { "1055", "Midlands Net Zero Hub" },
            { "1045", "Midlands Net Zero Hub" },
            { "4410", null },
            { "1265", "Dorset Council" },
            { "2220", "Dartford Borough Council" },
            { "4615", "Midlands Net Zero Hub" },
            { "9058", null },
            { "1355", null },
            { "5270", "Greater London Authority" },
            { "9060", null },
            { "510", "Cambridge City Council" },
            { "1105", "Devon County Council" },
            { "9061", null },
            { "1710", "Portsmouth City Council" },
            { "1915", "Cambridgeshire and Peterborough Combined Authority" },
            { "2510", "Midlands Net Zero Hub" },
            { "9062", null },
            { "9063", null },
            { "2001", null },
            { "3410", "Midlands Net Zero Hub" },
            { "3540", "Suffolk County Council" },
            { "1410", "Lewes District Council" },
            { "1715", "Portsmouth City Council" },
            { "3605", "Surrey County Council" },
            { "5300", "Greater London Authority" },
            { "1535", "Cambridgeshire and Peterborough Combined Authority" },
            { "3610", "Surrey County Council" },
            { "1025", "Midlands Net Zero Hub" },
            { "1110", "Devon County Council" },
            { "9065", null },
            { "1720", "Portsmouth City Council" },
            { "515", "Cambridge City Council" },
            { "9066", null },
            { "6835", null },
            { "2250", "Cambridgeshire and Peterborough Combined Authority" },
            { "1615", "Stroud District Council" },
            { "2325", null },
            { "4505", null },
            { "3020", "Midlands Net Zero Hub" },
            { "1620", "Stroud District Council" },
            { "1725", "Portsmouth City Council" },
            { "2230", "Cambridgeshire and Peterborough Combined Authority" },
            { "2615", null },
            { "5330", "Greater London Authority" },
            { "3615", "Surrey County Council" },
            { "6810", null },
            { "5360", "Greater London Authority" },
            { "650", "Liverpool City Region Combined Authority" },
            { "5390", "Greater London Authority" },
            { "2415", "Midlands Net Zero Hub" },
            { "1540", "Cambridgeshire and Peterborough Combined Authority" },
            { "5450", "Greater London Authority" },
            { "1730", "Cambridgeshire and Peterborough Combined Authority" },
            { "724", "Darlington Borough Council" },
            { "1415", "Lewes District Council" },
            { "1735", "Portsmouth City Council" },
            { "5480", "Cambridgeshire and Peterborough Combined Authority" },
            { "1850", "Midlands Net Zero Hub" },
            { "1920", "Cambridgeshire and Peterborough Combined Authority" },
            { "1030", "Midlands Net Zero Hub" },
            { "9068", null },
            { "5510", "Greater London Authority" },
            { "2420", "Midlands Net Zero Hub" },
            { "3825", "Portsmouth City Council" },
            { "520", "Cambridge City Council" },
            { "2330", "Blackpool Council" },
            { "9069", null },
            { "3515", "Suffolk County Council" },
            { "6805", null },
            { "2114", "Portsmouth City Council" },
            { "835", "Cornwall Council and Council of the Isles of Scilly" },
            { "5570", "Greater London Authority" },
            { "5600", "Greater London Authority" },
            { "2635", "Broadland District Council" },
            { "2004", null },
            { "5630", "Greater London Authority" },
            { "4715", null },
            { "4305", "Liverpool City Region Combined Authority" },
            { "5660", "Greater London Authority" },
            { "2335", "Blackpool Council" },
            { "4720", null },
            { "2465", null },
            { "1425", "Lewes District Council" },
            { "5690", "Greater London Authority" },
            { "3415", "Midlands Net Zero Hub" },
            { "2515", "Midlands Net Zero Hub" },
            { "4310", "Liverpool City Region Combined Authority" },
            { "5180", "Greater London Authority" },
            { "5420", "Greater London Authority" },
            { "5540", "Greater London Authority" },
            { "230", null },
            { "2235", "Cambridgeshire and Peterborough Combined Authority" },
            { "1545", "Cambridgeshire and Peterborough Combined Authority" },
            { "1820", "Midlands Net Zero Hub" },
            { "4215", null },
            { "3025", "Midlands Net Zero Hub" },
            { "2280", "Cambridgeshire and Peterborough Combined Authority" },
            { "2430", "Midlands Net Zero Hub" },
            { "6925", null },
            { "5720", "Greater London Authority" },
            { "1135", "Devon County Council" },
            { "3520", "Suffolk County Council" },
            { "3830", "Portsmouth City Council" },
            { "734", null },
            { "9070", null },
            { "435", "Cambridgeshire and Peterborough Combined Authority" },
            { "3620", "Surrey County Council" },
            { "6840", null },
            { "9071", null },
            { "6930", null },
            { "1740", "Portsmouth City Council" },
            { "3030", "Midlands Net Zero Hub" },
            { "4510", null },
            { "3420", "Midlands Net Zero Hub" },
            { "5750", "Greater London Authority" },
            { "6935", null },
            { "9072", null },
            { "1115", "Devon County Council" },
            { "1035", null },
            { "2002", "Midlands Net Zero Hub" },
            { "1925", "Cambridgeshire and Peterborough Combined Authority" },
            { "2520", "Midlands Net Zero Hub" },
            { "9073", null },
            { "2003", "Midlands Net Zero Hub" },
            { "2620", "Broadland District Council" },
            { "2840", "Cambridgeshire and Peterborough Combined Authority" },
            { "121", "Bristol City Council" },
            { "4515", null },
            { "3705", "Midlands Net Zero Hub" },
            { "2435", "Midlands Net Zero Hub" },
            { "2745", "North Yorkshire Council" },
            { "2935", null },
            { "2625", "Broadland District Council" },
            { "3060", "Midlands Net Zero Hub" },
            { "3710", "Midlands Net Zero Hub" },
            { "2440", "Midlands Net Zero Hub" },
            { "4220", null },
            { "7655", null },
            { "9000", null },
            { "3110", "Cambridgeshire and Peterborough Combined Authority" },
            { "6845", null },
            { "2340", "Blackpool Council" },
            { "9074", null },
            { "540", "Portsmouth City Council" },
            { "1160", null },
            { "1775", "Portsmouth City Council" },
            { "6850", null },
            { "2345", "Blackpool Council" },
            { "345", "Cambridgeshire and Peterborough Combined Authority" },
            { "5780", "Greater London Authority" },
            { "728", "Darlington Borough Council" },
            { "1825", "Midlands Net Zero Hub" },
            { "3625", "Surrey County Council" },
            { "9075", null },
            { "6940", null },
            { "2350", "Blackpool Council" },
            { "5810", "Greater London Authority" },
            { "4225", null },
            { "1550", "Cambridgeshire and Peterborough Combined Authority" },
            { "2355", "Blackpool Council" },
            { "1430", "Lewes District Council" },
            { "4415", null },
            { "3715", "Midlands Net Zero Hub" },
            { "3630", "Surrey County Council" },
            { "3040", "Midlands Net Zero Hub" },
            { "1750", "Portsmouth City Council" },
            { "2470", "Portsmouth City Council" },
            { "4230", null },
            { "4620", "Midlands Net Zero Hub" },
            { "9055", null },
            { "4320", "Liverpool City Region Combined Authority" },
            { "2245", null },
            { "4420", null },
            { "9010", null },
            { "3245", "Midlands Net Zero Hub" },
            { "350", "Cambridgeshire and Peterborough Combined Authority" },
            { "4625", "Midlands Net Zero Hub" },
            { "3300", null },
            { "9076", null },
            { "530", "Cambridge City Council" },
            { "1040", "Midlands Net Zero Hub" },
            { "119", "Stroud District Council" },
            { "1125", "West Devon Borough Council" },
            { "2525", "Midlands Net Zero Hub" },
            { "2530", "Midlands Net Zero Hub" },
            { "9077", null },
            { "2630", "Broadland District Council" },
            { "3115", "Oxfordshire County Council" },
            { "2360", "Blackpool Council" },
            { "3430", "Midlands Net Zero Hub" },
            { "4520", null },
            { "1780", "Portsmouth City Council" },
            { "1590", "Cambridgeshire and Peterborough Combined Authority" },
            { "5840", "Greater London Authority" },
            { "3635", "Surrey County Council" },
            { "1930", "Cambridgeshire and Peterborough Combined Authority" },
            { "4315", "Liverpool City Region Combined Authority" },
            { "3425", "Midlands Net Zero Hub" },
            { "3435", "Midlands Net Zero Hub" },
            { "1935", "Cambridgeshire and Peterborough Combined Authority" },
            { "9078", null },
            { "4235", null },
            { "738", "Darlington Borough Council" },
            { "3720", "Midlands Net Zero Hub" },
            { "1625", "Stroud District Council" },
            { "4525", null },
            { "3640", "Surrey County Council" },
            { "5870", "Cambridgeshire and Peterborough Combined Authority" },
            { "2255", "Cambridgeshire and Peterborough Combined Authority" },
            { "6855", null },
            { "3935", null },
            { "4240", null },
            { "3445", "Midlands Net Zero Hub" },
            { "3645", "Surrey County Council" },
            { "1130", "Devon County Council" },
            { "3240", "Midlands Net Zero Hub" },
            { "1560", "Cambridgeshire and Peterborough Combined Authority" },
            { "1760", "Portsmouth City Council" },
            { "1630", "Stroud District Council" },
            { "2260", "Cambridgeshire and Peterborough Combined Authority" },
            { "1940", null },
            { "1595", "Cambridgeshire and Peterborough Combined Authority" },
            { "2265", "Cambridgeshire and Peterborough Combined Authority" },
            { "1165", "Devon County Council" },
            { "6945", null },
            { "1145", "Devon County Council" },
            { "5900", "Greater London Authority" },
            { "4245", null },
            { "2270", "Cambridgeshire and Peterborough Combined Authority" },
            { "1570", "Cambridgeshire and Peterborough Combined Authority" },
            { "6950", null },
            { "3120", "Oxfordshire County Council" },
            { "4725", null },
            { "4630", "Midlands Net Zero Hub" },
            { "5930", "Greater London Authority" },
            { "5960", "Greater London Authority" },
            { "655", null },
            { "3725", "Midlands Net Zero Hub" },
            { "1945", null },
            { "3650", "Surrey County Council" },
            { "1435", null },
            { "1950", "Cambridgeshire and Peterborough Combined Authority" },
            { "340", "Cambridgeshire and Peterborough Combined Authority" },
            { "1150", "West Devon Borough Council" },
            { "9057", null },
            { "2365", "Blackpool Council" },
            { "2535", "Midlands Net Zero Hub" },
            { "9079", null },
            { "2845", "Cambridgeshire and Peterborough Combined Authority" },
            { "3125", "Oxfordshire County Council" },
            { "3545", "Suffolk County Council" },
            { "9020", null },
            { "935", "Cumberland Council and Westmoreland and Furness" },
            { "4250", null },
            { "3940", null },
            { "1765", "Portsmouth City Council" },
            { "355", "Cambridgeshire and Peterborough Combined Authority" },
            { "4325", "Liverpool City Region Combined Authority" },
            { "3655", "Surrey County Council" },
            { "360", "Cambridgeshire and Peterborough Combined Authority" },
            { "4635", "Midlands Net Zero Hub" },
            { "1835", "Midlands Net Zero Hub" },
            { "1855", "Midlands Net Zero Hub" },
            { "3835", "Portsmouth City Council" },
            { "6955", null },
            { "1840", "Midlands Net Zero Hub" },
            { "2370", "Blackpool Council" },
            { "1845", "Midlands Net Zero Hub" },
            { "2741", null }
        };
    }
}