using System.Collections.Generic;
using WhlgPublicWebsite.BusinessLogic.Models;

namespace Tests.BusinessLogic.Models.ExpectedLocalAuthorityData;

internal static class LocalAuthorityConsortiums
{
    // This dictionary data is automatically generated
    // See https://github.com/UKGovernmentBEIS/desnz-warm-homes-local-grant/tree/develop/scripts/local-authority-information-generators
    // Avoid making manual changes to this code if possible
    internal static Dictionary<string, string> ConsortiumsByCustodianCode()
    {
        return new Dictionary<string, string>
        {
            { "9051", "Turner and Townsend" },
            { "9052", null },
            { "3805", "Portsmouth City Council" },
            { "1005", "Nottingham City Council" },
            { "9053", null },
            { "9054", null },
            { "3810", "Portsmouth City Council" },
            { "3005", null },
            { "2205", null },
            { "3505", "Suffolk County Council" },
            { "5090", "Greater London Authority" },
            { "4405", null },
            { "1505", "Turner and Townsend" },
            { "1705", "Portsmouth City Council" },
            { "3010", "Nottingham City Council" },
            { "114", "Bristol City Council" },
            { "235", "Portsmouth City Council" },
            { "4605", "West Midlands Combined Authority" },
            { "2405", "Nottingham City Council" },
            { "2372", "Blackpool Council" },
            { "2373", "Blackpool Council" },
            { "6910", null },
            { "1010", "Nottingham City Council" },
            { "4205", "Greater Manchester Combined Authority" },
            { "1905", null },
            { "2505", "East Lindsey District Council" },
            { "1260", "Dorset Council" },
            { "335", "Portsmouth City Council" },
            { "1510", "Essex County Council" },
            { "2605", "Broadland District Council" },
            { "5150", "Greater London Authority" },
            { "1515", "Essex County Council" },
            { "6915", null },
            { "1445", "Portsmouth City Council" },
            { "116", "Bristol City Council" },
            { "2610", "Broadland District Council" },
            { "1805", "Nottingham City Council" },
            { "3015", "Nottingham City Council" },
            { "440", null },
            { "2315", "Blackpool Council" },
            { "4210", "Turner and Townsend" },
            { "6920", null },
            { "4710", null },
            { "505", "Cambridge City Council" },
            { "5210", "Greater London Authority" },
            { "3405", "Nottingham City Council" },
            { "2210", null },
            { "6825", null },
            { "1520", "Essex County Council" },
            { "240", null },
            { "6820", null },
            { "2410", "Nottingham City Council" },
            { "1525", "Essex County Council" },
            { "1605", "Stroud District Council" },
            { "3105", "Oxfordshire County Council" },
            { "660", "Cheshire East Council" },
            { "665", "Cheshire East Council" },
            { "1015", "Nottingham City Council" },
            { "3815", "Portsmouth City Council" },
            { "2320", "Blackpool Council" },
            { "6855", null },
            { "4705", null },
            { "6815", null },
            { "4410", null },
            { "9064", null },
            { "5030", "Greater London Authority" },
            { "2741", "Turner and Townsend" },
            { "9056", null },
            { "1530", "Essex County Council" },
            { "9020", null },
            { "6905", null },
            { "840", "Cornwall Council" },
            { "1610", "Stroud District Council" },
            { "4610", "West Midlands Combined Authority" },
            { "3820", "Portsmouth City Council" },
            { "5240", "Portsmouth City Council" },
            { "940", "Westmorland and Furness Council" },
            { "1910", null },
            { "1350", "Darlington Borough Council (Tees Consortium)" },
            { "2215", "Dover District Council" },
            { "6830", null },
            { "1055", "Nottingham City Council" },
            { "1045", "Nottingham City Council" },
            { "1155", "Devon County Council" },
            { "1265", "Dorset Council" },
            { "2220", "Dover District Council" },
            { "4615", "West Midlands Combined Authority" },
            { "9058", null },
            { "9059", null },
            { "1355", null },
            { "5270", "Greater London Authority" },
            { "9060", null },
            { "510", "Cambridge City Council" },
            { "1105", "Devon County Council" },
            { "9061", null },
            { "1710", "Portsmouth City Council" },
            { "1915", null },
            { "2510", "East Lindsey District Council" },
            { "9062", null },
            { "9063", null },
            { "2001", null },
            { "3410", "Nottingham City Council" },
            { "3540", "Suffolk County Council" },
            { "1440", "Lewes District Council" },
            { "1410", "Lewes District Council" },
            { "1715", "Portsmouth City Council" },
            { "3605", "Surrey County Council" },
            { "5300", "Greater London Authority" },
            { "1535", "Essex County Council" },
            { "3610", "Surrey County Council" },
            { "1025", "Nottingham City Council" },
            { "1585", "Essex County Council" },
            { "1110", "Devon County Council" },
            { "9065", null },
            { "1720", "Portsmouth City Council" },
            { "515", "Cambridge City Council" },
            { "9066", null },
            { "6835", null },
            { "2250", null },
            { "1615", "Stroud District Council" },
            { "2325", null },
            { "4505", null },
            { "3020", "Nottingham City Council" },
            { "9067", null },
            { "1620", "Stroud District Council" },
            { "1725", "Portsmouth City Council" },
            { "2230", null },
            { "2615", null },
            { "3615", "Surrey County Council" },
            { "6810", null },
            { "5360", "Greater London Authority" },
            { "650", "Liverpool City Region Combined Authority" },
            { "2415", "Nottingham City Council" },
            { "5420", "Greater London Authority" },
            { "1540", "Essex County Council" },
            { "1730", "Portsmouth City Council" },
            { "724", null },
            { "1415", "Lewes District Council" },
            { "1735", "Portsmouth City Council" },
            { "1850", "Shropshire County Council" },
            { "1920", null },
            { "1030", "Nottingham City Council" },
            { "5510", "Greater London Authority" },
            { "2420", "Nottingham City Council" },
            { "3825", "Portsmouth City Council" },
            { "2004", null },
            { "520", "Cambridge City Council" },
            { "2330", "Blackpool Council" },
            { "9069", null },
            { "3515", "Suffolk County Council" },
            { "6805", null },
            { "2114", "Portsmouth City Council" },
            { "835", "Cornwall Council" },
            { "5570", "Greater London Authority" },
            { "2635", "Broadland District Council" },
            { "4715", null },
            { "4305", "Liverpool City Region Combined Authority" },
            { "5660", "Greater London Authority" },
            { "2335", "Blackpool Council" },
            { "4720", null },
            { "2465", "Turner and Townsend" },
            { "1425", "Lewes District Council" },
            { "5690", "Greater London Authority" },
            { "3415", "Nottingham City Council" },
            { "2515", "Nottingham City Council" },
            { "4310", "Liverpool City Region Combined Authority" },
            { "5060", null },
            { "5120", "Greater London Authority" },
            { "5180", "Greater London Authority" },
            { "5390", "Greater London Authority" },
            { "5450", "Greater London Authority" },
            { "5480", "Greater London Authority" },
            { "5540", "Greater London Authority" },
            { "5720", "Greater London Authority" },
            { "5780", "Greater London Authority" },
            { "5810", "Greater London Authority" },
            { "5870", "Greater London Authority" },
            { "5930", "Greater London Authority" },
            { "230", "Portsmouth City Council" },
            { "2235", null },
            { "1545", "Essex County Council" },
            { "1820", "Nottingham City Council" },
            { "4215", "Greater Manchester Combined Authority" },
            { "3025", "Nottingham City Council" },
            { "2280", null },
            { "2430", "Nottingham City Council" },
            { "6925", null },
            { "1135", "Devon County Council" },
            { "3520", "Suffolk County Council" },
            { "3830", "Portsmouth City Council" },
            { "734", "Darlington Borough Council (Tees Consortium)" },
            { "9070", null },
            { "435", "Portsmouth City Council" },
            { "3620", "Surrey County Council" },
            { "6840", null },
            { "6930", null },
            { "1740", "Portsmouth City Council" },
            { "3030", "Nottingham City Council" },
            { "4510", "Turner and Townsend" },
            { "3420", "Nottingham City Council" },
            { "5750", "Greater London Authority" },
            { "6935", null },
            { "9072", null },
            { "1115", "Devon County Council" },
            { "1035", null },
            { "2002", "Nottingham City Council" },
            { "1925", null },
            { "2520", "Nottingham City Council" },
            { "9073", null },
            { "2003", "Nottingham City Council" },
            { "2620", "Broadland District Council" },
            { "2840", null },
            { "121", "Bristol City Council" },
            { "4515", null },
            { "3705", "Nottingham City Council" },
            { "2435", "Nottingham City Council" },
            { "2745", null },
            { "2935", null },
            { "2625", null },
            { "3060", "Nottingham City Council" },
            { "3710", "Nottingham City Council" },
            { "2440", "Nottingham City Council" },
            { "4220", "Greater Manchester Combined Authority" },
            { "9000", null },
            { "3110", "Oxfordshire County Council" },
            { "3100", "Oxfordshire County Council" },
            { "6845", null },
            { "2340", "Blackpool Council" },
            { "9074", null },
            { "540", "Cambridge City Council" },
            { "1160", null },
            { "1775", "Portsmouth City Council" },
            { "6850", null },
            { "2345", "Blackpool Council" },
            { "345", "Portsmouth City Council" },
            { "728", "Darlington Borough Council (Tees Consortium)" },
            { "1825", "Nottingham City Council" },
            { "3625", "Surrey County Council" },
            { "9075", null },
            { "6940", null },
            { "2350", "Blackpool Council" },
            { "4225", "Greater Manchester Combined Authority" },
            { "1550", "Essex County Council" },
            { "2355", "Blackpool Council" },
            { "1430", "Lewes District Council" },
            { "4415", null },
            { "5330", "Greater London Authority" },
            { "5600", "Greater London Authority" },
            { "5630", "Greater London Authority" },
            { "355", "Portsmouth City Council" },
            { "3715", "Nottingham City Council" },
            { "3630", "Surrey County Council" },
            { "3040", "Nottingham City Council" },
            { "1750", "Portsmouth City Council" },
            { "2470", "Portsmouth City Council" },
            { "4230", "Greater Manchester Combined Authority" },
            { "4620", "West Midlands Combined Authority" },
            { "9055", null },
            { "4320", "Liverpool City Region Combined Authority" },
            { "2245", null },
            { "4420", null },
            { "9010", null },
            { "3245", "Shropshire County Council" },
            { "350", null },
            { "4625", "West Midlands Combined Authority" },
            { "3300", null },
            { "9076", null },
            { "530", "Cambridge City Council" },
            { "1040", "Nottingham City Council" },
            { "119", "Stroud District Council" },
            { "1125", "West Devon Borough Council" },
            { "2525", "East Lindsey District Council" },
            { "2530", "Nottingham City Council" },
            { "9077", null },
            { "2630", "Broadland District Council" },
            { "3115", "Oxfordshire County Council" },
            { "2360", "Blackpool Council" },
            { "3430", "Nottingham City Council" },
            { "4520", null },
            { "1780", "Portsmouth City Council" },
            { "1590", "Essex County Council" },
            { "5840", "Greater London Authority" },
            { "3635", "Surrey County Council" },
            { "1930", null },
            { "4315", "Liverpool City Region Combined Authority" },
            { "3425", "Nottingham City Council" },
            { "3435", "Nottingham City Council" },
            { "1935", null },
            { "9078", null },
            { "4235", null },
            { "738", "Darlington Borough Council (Tees Consortium)" },
            { "3455", "Nottingham City Council" },
            { "3720", "Nottingham City Council" },
            { "1625", "Stroud District Council" },
            { "3500", "Suffolk County Council" },
            { "4525", null },
            { "3600", "Surrey County Council" },
            { "3640", "Surrey County Council" },
            { "2255", null },
            { "3935", null },
            { "4240", "Greater Manchester Combined Authority" },
            { "3445", "Nottingham City Council" },
            { "3645", "Surrey County Council" },
            { "1130", "Devon County Council" },
            { "3240", "Shropshire County Council" },
            { "1560", "Essex County Council" },
            { "1760", "Portsmouth City Council" },
            { "1630", "Stroud District Council" },
            { "2260", null },
            { "9068", null },
            { "9071", null },
            { "1940", "Watford Borough Council" },
            { "1595", "Essex County Council" },
            { "2265", null },
            { "1165", "Devon County Council" },
            { "6945", null },
            { "1145", "Devon County Council" },
            { "5900", "Greater London Authority" },
            { "4245", "Greater Manchester Combined Authority" },
            { "2270", null },
            { "1570", "Essex County Council" },
            { "6950", null },
            { "3120", "Oxfordshire County Council" },
            { "4725", null },
            { "4630", "West Midlands Combined Authority" },
            { "5960", "Greater London Authority" },
            { "655", "Cheshire East Council" },
            { "3725", "Nottingham City Council" },
            { "1945", "Watford Borough Council" },
            { "3650", "Surrey County Council" },
            { "1435", "Lewes District Council" },
            { "1950", null },
            { "340", "Portsmouth City Council" },
            { "1150", "West Devon Borough Council" },
            { "9057", null },
            { "2365", "Blackpool Council" },
            { "2535", "Nottingham City Council" },
            { "9079", null },
            { "2845", null },
            { "3125", "Oxfordshire County Council" },
            { "3545", "Suffolk County Council" },
            { "5990", "Greater London Authority" },
            { "935", "Westmorland and Furness Council" },
            { "4250", "Greater Manchester Combined Authority" },
            { "3940", null },
            { "1765", "Portsmouth City Council" },
            { "4325", "Liverpool City Region Combined Authority" },
            { "3655", "Surrey County Council" },
            { "360", "Portsmouth City Council" },
            { "4635", "West Midlands Combined Authority" },
            { "1835", "Nottingham City Council" },
            { "1855", null },
            { "3835", "Portsmouth City Council" },
            { "6955", null },
            { "1840", "Nottingham City Council" },
            { "2370", "Blackpool Council" },
            { "1845", null },
        };
    }
}